package com.orm;

/**
 * TBook generated by MyEclipse Persistence Tools
 */

public class TBook implements java.io.Serializable {

    // Fields

    private Integer id;
    private String name;
    private String author;
    private String publisher;
    private String publication_time;
    private String isbn;
    private String price;
    private String pages;
    private String language;
    private String stock;
    private int catelog_id;
    private String del;


    public TBook() {

    }

    public String getPublication_time() {
        return publication_time;
    }

    public void setPublication_time(String publication_time) {
        this.publication_time = publication_time;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }


    public int getCatelog_id() {
        return catelog_id;
    }

    public void setCatelog_id(int catelog_id) {
        this.catelog_id = catelog_id;
    }

    public String getPublicationDate() {
        return publication_time;
    }

    public void setPublicationDate(String publication_time) {
        this.publication_time = publication_time;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getDel() {
        return del;
    }

    public void setDel(String del) {
        this.del = del;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getStock() {
        return stock;
    }

    public void setStock(String stock) {
        this.stock = stock;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getPages() {
        return pages;
    }

    public void setPages(String pages) {
        this.pages = pages;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }


}