package com.orm;

/**
 * Torder generated by MyEclipse Persistence Tools
 */

public class TOrder implements java.io.Serializable {

    private Integer id;
    private int user_id;
    private int book_id;
    private int order_num;
    private String order_time;
    private String del;
    private TCustomer user;
    private TBook book;

    public int getBook_id() {
        return book_id;
    }

    public void setBook_id(int book_id) {
        this.book_id = book_id;
    }

    public String getDel() {
        return del;
    }

    public void setDel(String del) {
        this.del = del;
    }


    public Integer getId() {
        return id;
    }

    public TBook getBook() {
        return book;
    }

    public void setBook(TBook book) {
        this.book = book;
    }

    public TCustomer getUser() {
        return user;
    }

    public void setUser(TCustomer user) {
        this.user = user;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOrder_time() {
        return order_time;
    }

    public void setOrder_time(String order_time) {
        this.order_time = order_time;
    }

    public int getOrder_num() {
        return order_num;
    }

    public void setOrder_num(int order_num) {
        this.order_num = order_num;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

}